"""
This script defines a common embedding pipeline interface and two concrete pipelines:
SCVI and PCA. 

For each pipeline the following methods are implemented: 

1. Preprocess
2. Fit
3. Get_latent
4. Visualization (t-SNE and UMAP)
5. Clustering (Leiden)
6. Save
"""

from abc import ABC, abstractmethod
import numpy as np
import scvi
import anndata
import scanpy as sc
import time
from functools import wraps
import joblib
from dataclasses import dataclass, field
from typing import Optional


def timeit_store(method):
    """
    Measure and store the execution time of a pipeline method.

    Args:
        method: The method to be timed.

    Returns:
        The wrapped method that stores elapsed runtime in self.timings using
        the original method name as the key.
    """
    @wraps(method)
    def timed(self, *args, **kwargs):
        start = time.time()
        result = method(self, *args, **kwargs)
        end = time.time()
        elapsed = end - start

        # Initialize timing dictionary if it doesn't exist
        if not hasattr(self, "timings"):
            self.timings = {}

        # Store the elapsed time under the method's name
        self.timings[method.__name__] = elapsed
        return result

    return timed


@dataclass
class PipelineResults:
    """
    Container for outputs generated by an embedding pipeline.

    Attributes:
        timings: Runtime measurements for timed pipeline steps.
        parameters: Parameters used to instantiate the pipeline.
        losses: Losses computed during training (if applicable).
        additional: Any additional outputs generated by the pipeline.
        preprocessed: Preprocessed data (if applicable).
        embeddings: Latent embeddings generated by the pipeline.
        tsne: t-SNE coordinates.
        umap: UMAP coordinates.
        leiden: Leiden cluster assignment.
    """
    timings: dict = field(default_factory=dict)
    parameters: dict = field(default_factory=dict)
    losses: dict = field(default_factory=dict)
    additional: dict = field(default_factory=dict)
    preprocessed: Optional[np.ndarray] = None
    embeddings: Optional[np.ndarray] = None
    tsne: Optional[np.ndarray] = None
    umap: Optional[np.ndarray] = None
    leiden: Optional[np.ndarray] = None


class EmbeddingPipeline(ABC):
    """
    Abstract base class defining the required interface for embedding pipelines. 
    """
    @abstractmethod
    def preprocess(self, data):
        pass

    @abstractmethod
    def fit(self):
        pass

    @abstractmethod
    def get_latent(self, data=None):
        pass

    @abstractmethod
    def visualization(self):
        pass

    @abstractmethod
    def clustering(self):
        pass

    @abstractmethod
    def save(self, path):
        pass


class SCVI(EmbeddingPipeline):
    """
    Embedding pipeline based on scVI.
    """
    def __init__(
        self,
        n_latent,
        n_hidden,
        n_layers,
        likelihood,
        n_epochs,
        batch_size,
        highly_variable_genes,
        device,
        seed,
        unique_groups,
        **kwargs,
    ):
        """
        Initialize the scVI pipeline.

        Args:
            n_latent: Number of latent dimensions for the scVI model.
            n_hidden: Number of hidden units in each neural network layer.
            n_layers: Number of neural network layers.
            likelihood: Gene likelihood model used by scVI.
            n_epochs: Number of training epochs.
            highly_variable_genes: Whether to subset to highly variable genes.
            batch_size: Training batch size.
            device: Device setting for computation.
            seed: Random seed used for reproducibility.
            **kwargs: Additional unused keyword arguments.
        
        Returns:
            None
        """
        self.n_latent = n_latent
        self.n_hidden = n_hidden
        self.n_layers = n_layers
        self.likelihood = likelihood
        self.n_epochs = n_epochs
        self.highly_variable_genes = highly_variable_genes
        self.batch_size = batch_size
        self.device = device
        self.unique_groups = unique_groups
        params = self.__dict__.copy()
        self.seed = seed
        self.results = PipelineResults()
        self.results.parameters = params
        self.adata = None
        self.model = None

    @timeit_store
    def preprocess(self, data):
        """
        Prepare data for scVI training.

        Args:
            data: AnnData object or matrix-like input data.
        
        Returns:
            None
        """
        if not isinstance(data, anndata.AnnData):
            self.adata = anndata.AnnData(data)
            batch_key = None
            layer = None
        else:
            self.adata = data.copy()
            batch_key = "donor" if "donor" in self.adata.obs.columns else None
            layer = "raw_counts" if "raw_counts" in self.adata.layers.keys() else None

        if self.highly_variable_genes:
            sc.pp.highly_variable_genes(
                self.adata, flavor="seurat_v3", n_top_genes=2000
            )
            self.adata = self.adata[:, self.adata.var["highly_variable"]].copy()

        scvi.model.SCVI.setup_anndata(self.adata, batch_key=batch_key, layer=layer)
        self.model = scvi.model.SCVI(
            self.adata,
            n_latent=self.n_latent,
            n_hidden=self.n_hidden,
            n_layers=self.n_layers,
            gene_likelihood=self.likelihood,
        )

    @timeit_store
    def fit(self):
        """
        Train the scVI model on preprocessed data.

        Args:
            None

        Returns:
            None

        Raises:
            ValueError: If preprocess() has not been called before fitting.
        """
        if self.adata is None:
            raise ValueError("Data not preprocessed. Call preprocess() first.")
        self.model.train(
            self.n_epochs, batch_size=self.batch_size, enable_progress_bar=False
        )
        # Store training history for loss-vs-epoch plots
        self.history = getattr(self.model, "history_", None)

    @timeit_store
    def get_latent(self, data=None):
        """
        Compute and return the latent embedding representation.

        Args:
            data: Optional input data. Currently unused.

        Returns:
            scVI latent representation stored in adata.obsm["X_scVI"].
        """
        self.adata.obsm["X_scVI"] = self.model.get_latent_representation()
        return self.adata.obsm["X_scVI"]

    def visualization(self):
        """
        Calls all visualization methods: UMAP and t-SNE.

        Args:
            None

        Returns:
            None

        Raises:
            ValueError: If the model has not been trained.
        """
        if self.model is None:
            raise ValueError("Model not trained. Call fit() first.")
        else:
            self.tsne()
            self.umap()

    @timeit_store
    def tsne(self):
        """
        Compute t-SNE coordinates using the scVI latent representation.

        Args:
            None

        Returns:
            None
        """
        sc.tl.tsne(self.adata, use_rep="X_scVI", random_state=self.seed)

    @timeit_store
    def umap(self):
        """
        Compute nearest neighbors and UMAP coordinates using the scVI latent representation.

        Args:
            None

        Returns:
            None
        """
        sc.pp.neighbors(self.adata, use_rep="X_scVI")
        sc.tl.umap(self.adata, random_state=self.seed)

    def clustering(self):
        """
        Run clustering methods for the scVI latent representation.

        Args:
            None

        Returns:
            None

        Raises:
            ValueError: If the model has not been trained.
        """
        if self.model is None:
            raise ValueError("Model not trained. Call fit() first.")
        else:
            self.leiden()

    @timeit_store
    def leiden(self):
        """
        Perform Leiden clustering on the scVI latent representation.

        The method searches for a resolution that produces the target number of clusters.

        Args:
            None

        Returns:
            None

        Raises:
            RuntimeError: If the target number of clusters cannot be reached.
        """
        sc.pp.neighbors(self.adata, use_rep="X_scVI")
        target_clusters = self.unique_groups
        resolution = 0.5
        min_res = 0.00000001
        max_res = 20
        max_iter = 500
        for _ in range(max_iter):
            sc.tl.leiden(
                self.adata,
                flavor="igraph",
                n_iterations=2,
                random_state=self.seed,
                resolution=resolution,
            )
            nclusters = len(self.adata.obs["leiden"].unique())

            if nclusters == target_clusters:
                return
            if nclusters > target_clusters:
                # too many clusters, lower resolution
                resolution = max(min_res, resolution * 0.5)
            else:
                # too few clusters, increase resolution
                resolution = min(max_res, resolution * 1.5)
        else:
            raise RuntimeError(
                f"Could not reach target clusters; last result had {nclusters} clusters at resolution {resolution:.2f}"
            )

    def save(self, filename, **kwargs):
        """
        Save scVI pipeline results to a pickle file.

        Stores timings, t-SNE coordinates, UMAP coordinates, Leiden labels, loss values,
        additional metadata, and training history when available.

        Args:
            filename: Output filename prefix. The method writes "{filename}.pkl".
            **kwargs: Additional metadata to store in the results object.

        Returns:
            None
        """
        self.results.timings = self.timings
        # self.results.embeddings = self.adata.obsm["X_scVI"]
        self.results.tsne = self.adata.obsm["X_tsne"]
        self.results.umap = self.adata.obsm["X_umap"]
        self.results.leiden = self.adata.obs["leiden"]

        ### losses
        recon_loss = -self.model.get_reconstruction_error(return_mean=True)[
            "reconstruction_loss"
        ].item()
        total = -self.model.get_elbo(return_mean=True).item()
        kl_loss = total - recon_loss
        losses = {
            "reconstruction_loss": recon_loss,
            "kl_loss": kl_loss,
            "elbo": total,
        }
        self.results.losses = losses
        self.results.additional = kwargs
        if getattr(self, "history", None) is not None:
            try:
                self.results.additional["training_history"] = (
                    self.history.reset_index().to_dict(orient="list")
                )
            except Exception:
                self.results.additional["training_history"] = self.history
        joblib.dump(self.results, f"{filename}.pkl")  # save results
        # self.model.save(f"{filename}_model.pt")  # save model


class PCA(EmbeddingPipeline):
    """
    Embedding pipeline based on principal component analysis.
    """
    def __init__(
        self,
        n_components,
        highly_variable_genes,
        normalize_total,
        log1p,
        scale,
        seed,
        unique_groups,
        **kwargs,
    ):
        """
        Initialize the PCA pipeline.

        Args:
            n_components: Number of PCA components to compute.
            highly_variable_genes: Whether to subset to highly variable genes.
            normalize_total: Whether to normalize counts per cell.
            log1p: Whether to apply log1p transformation.
            scale: Whether to scale features before PCA.
            seed: Random seed used for reproducibility.
            **kwargs: Additional unused keyword arguments.

        Returns:
            None
        """
        self.n_components = n_components
        self.highly_variable_genes = highly_variable_genes
        self.normalize_total = normalize_total
        self.log1p = log1p
        self.scale = scale
        self.unique_groups = unique_groups
        params = self.__dict__.copy()
        self.seed = seed
        self.results = PipelineResults()
        self.results.parameters = params
        self.adata = None

    @timeit_store
    def preprocess(self, data):
        """
        Prepare data for PCA.

        Args:
            data: AnnData object or matrix-like input data.
        
        Returns:
            None
        """
        if not isinstance(data, anndata.AnnData):
            self.adata = anndata.AnnData(data)
        else:
            self.adata = data.copy()

        # Use raw counts for preprocessing
        if "raw_counts" in self.adata.layers:
            self.adata.X = self.adata.layers["raw_counts"].copy()
        else:
            pass

        if self.highly_variable_genes:
            sc.pp.highly_variable_genes(
                self.adata, flavor="seurat_v3", n_top_genes=2000
            )
            self.adata = self.adata[:, self.adata.var["highly_variable"]].copy()
        if self.normalize_total:
            sc.pp.normalize_total(self.adata, target_sum=1e4)
        if self.log1p:
            sc.pp.log1p(self.adata)
        if self.scale:
            sc.pp.scale(self.adata)

    @timeit_store
    def fit(self):
        """
        Compute PCA on preprocessed data.

        Args:
            None

        Returns:
            None

        Raises:
            ValueError: If preprocess() has not been called before fitting.
        """
        # Fit PCA model
        if self.adata is None:
            raise ValueError("Data not preprocessed. Call preprocess() first.")
        else:
            sc.tl.pca(self.adata, n_comps=self.n_components)

    @timeit_store
    def get_latent(self, data=None):
        """
        Compute and return the PCA embedding.

        Args:
            data: Optional input data. Currently unused.

        Returns:
            PCA embedding stored in adata.obsm["X_pca"].
        """
        return self.adata.obsm["X_pca"]

    def visualization(self):
        """
        Calls all visualization methods: UMAP and TSNE

        Args:
            None

        Returns:
            None

        Raises:
            ValueError: If PCA has not been computed.
        """
        if "X_pca" not in self.adata.obsm:
            raise ValueError("PCA not computed. Call preprocess() and fit() first.")
        self.tsne()
        self.umap()

    @timeit_store
    def tsne(self):
        """
        Compute t-SNE coordinates using the PCA embedding.

        Args:
            None

        Returns:
            None
        """
        sc.tl.tsne(self.adata, use_rep="X_pca", random_state=self.seed)

    @timeit_store
    def umap(self):
        """
        Compute nearest neighbors and UMAP coordinates using the PCA embedding.

        Args:
            None

        Returns:
            None
        """
        sc.pp.neighbors(self.adata, use_rep="X_pca")
        sc.tl.umap(self.adata, random_state=self.seed)

    def clustering(self):
        """
        Run clustering methods for the PCA embedding.

        Args:
            None

        Returns:
            None

        Raises:
            ValueError: If PCA has not been computed.
        """
        if "X_pca" not in self.adata.obsm:
            raise ValueError("PCA not computed. Call preprocess() and fit() first.")
        self.leiden()

    @timeit_store
    def leiden(self):
        """
        Perform Leiden clustering on the PCA embedding.

        The method searches for a resolution that produces the target number of clusters.

        Args:
            None

        Returns:
            None

        Raises:
            RuntimeError: If the target number of clusters cannot be reached.
        """
        sc.pp.neighbors(self.adata, use_rep="X_pca")
        target_clusters = self.unique_groups
        resolution = 0.5
        min_res = 0.00000001
        max_res = 20
        max_iter = 500
        for _ in range(max_iter):
            sc.tl.leiden(
                self.adata,
                flavor="igraph",
                n_iterations=2,
                random_state=self.seed,
                resolution=resolution,
            )
            nclusters = len(self.adata.obs["leiden"].unique())

            if nclusters == target_clusters:
                return
            if nclusters > target_clusters:
                # too many clusters, lower resolution
                resolution = max(min_res, resolution * 0.5)
            else:
                # too few clusters, increase resolution
                resolution = min(max_res, resolution * 1.5)
        else:
            raise RuntimeError(
                f"Could not reach target clusters; last result had {nclusters} clusters at resolution {resolution:.2f}"
            )

    def save(self, filename, **kwargs):
        """
        Save PCA pipeline results to a pickle file.

        Stores timings, t-SNE coordinates, UMAP coordinates, Leiden labels, and additional
        metadata.

        Args:
            filename: Output filename prefix. The method writes "{filename}.pkl".
            **kwargs: Additional metadata to store in the results object.

        Returns:
            None
        """
        self.results.timings = self.timings
        # self.results.embeddings = self.adata.obsm["X_pca"]
        self.results.tsne = self.adata.obsm["X_tsne"]
        self.results.umap = self.adata.obsm["X_umap"]
        self.results.leiden = self.adata.obs["leiden"]
        self.results.additional = kwargs
        joblib.dump(self.results, f"{filename}.pkl")
